name: ExecuShell

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Run manually from 'Actions' tab

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For committing
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          dir: ./
          git-name: ExecuShell Testing
          git-email: nicho@scapeville.com