name: ExecuShell

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/checkout@v3
      - uses: ./
        with:
          dir: ./
          git-name: ExecuShell Testing
          git-email: nicho@scapeville.com