name: Run tests

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          # chmod +x tests/run-tests.sh
          tests/run-tests.sh